# Generated by Django 5.1.5 on 2025-01-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adjustment',
            name='store',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='discount_method',
            field=models.CharField(choices=[('percentage', 'percentage'), ('flat', 'flat')], default='percentage', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock_alert',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tax_method',
            field=models.CharField(choices=[('inclusive', 'inclusive'), ('exclusive', 'exclusive')], default='inclusive', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.store'),
        ),
    ]
