# Generated by Django 5.1.5 on 2025-01-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adjustment_note_adjustment_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='core.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_product', to='core.product')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='core.store')),
            ],
        ),
    ]
