# Generated by Django 5.1.5 on 2025-01-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Cutomer', 'Cutomer')], default='Customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
